# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Group', folder: 'documentation', file: 'about-the-group.html'}
- {name: 'Research', folder: 'documentation', file: 'research.html'}
- {name: 'Publications', folder: 'documentation', file: 'publications.html'}
- {name: 'Group Members', folder: 'documentation', file: 'group-members.html'}
- {name: 'Photos', folder: 'documentation', file: 'LabPhotos.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/Inflammedlab'}
- {icon: 'wordpress', link:  'https://bryantblog27.wordpress.com/author/bryantblog27'}
- {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
